version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.1.4
    steps:
      - checkout
      - run: npm install
      - run: npm run assert-beautified
      - run: npm run jshint
      - run: npm run node-full-test
      - run: npm run browser-test
      - run: npm run browser-coverage-full-test
